### PR TITLE
Fix for discard init_args after class_path change causes error

### LINKED ISSUE #205: Discard `init_args` after `class_path` change causes error
## 🐛 Bug report

When composing configs, it appears that overwritten class paths do not properly drop the old `init_args` namespace, causing an error when the new class does not have the same `init_args`.

Here is the error message:

```bash
$ main fit --config config_1.yaml --config configs_2.yaml
/unix/atlastracking/svanstroud/miniconda3/envs/salt/lib/python3.10/site-packages/jsonargparse/typehints.py:909: UserWarning: Due to class_path change from 'models.GATv2Attention' to 'models.ScaledDotProductAttention', discarding init_args: {'num_heads': 8, 'head_dim': 16, 'activation': Namespace(class_path='torch.nn.SiLU')}.
  warnings.warn(
usage: main [-h] [-c CONFIG] [--print_config[=flags]] {fit,validate,test,predict,tune} ...
main: error: Parser key "model": Problem with given class_path 'models.Tagger':
    - Parser key "gnn": Does not validate against any of the Union subtypes
      Subtypes: (<class 'torch.nn.modules.module.Module'>, <class 'NoneType'>)
      Errors:
        - Problem with given class_path 'models.Transformer':
          - Parser key "attention": Problem with given class_path 'models.ScaledDotProductAttention':
              - 'Configuration check failed :: No action for destination key "num_heads" to check its value.'
        - Expected a <class 'NoneType'>
      Given value type: <class 'jsonargparse.namespace.Namespace'>
      Given value: Namespace(class_path='models.Transformer', init_args=Namespace(embd_dim=128, num_heads=8, num_layers=8, attention=Namespace(class_path='models.ScaledDotProductAttention', init_args=Namespace(num_heads=8, head_dim=16, activation=Namespace(class_path='torch.nn.SiLU'))), activation='SiLU', residual=True, norm_layer='LayerNorm', dropout=0.1, out_proj=False))

```
### Expected behavior

The overwriting class should not be required to have the same `init_args` as the overwritten class. 
It would also be nice to have an option to suppress the warning about overwritten args.

### Environment

- jsonargparse 4.18.0
- Python 3.10.6

### PR DESCRIPTION
**Pull request by mauvilsa**
## What does this PR do?

Fixes #205.

## Before submitting

- [x] Did you read the [contributing guideline](https://github.com/omni-us/jsonargparse/blob/master/CONTRIBUTING.rst)?
- [n/a] Did you update **the documentation**? (readme and public docstrings)
- [x] Did you write **unit tests** such that there is 100% coverage on related code? (required for bug fixes and new features)
- [x] Did you verify that new and existing **tests pass locally**?
- [x] Did you make sure that all changes preserve **backward compatibility**?
- [x] Did you update **the CHANGELOG**? (not for typos, docs, test updates, or minor internal changes/refactors)

### CODE REVIEW

**Comment by samvanstroud** [comment]
Thanks a lot @mauvilsa. I am still having issues when overwriting one class with another. I am going from a submodule with `init_args` provided to one without.

```bash
.../lib/python3.10/site-packages/jsonargparse/typehints.py:909: UserWarning: Due to class_path change from 'models.GATv2Attention' to 'models.ScaledDotProductAttention', discarding init_args: {'num_heads': 8, 'head_dim': 16}.
  warnings.warn(
usage: main [-h] [-c CONFIG] [--print_config[=flags]] {fit,validate,test,predict,tune} ...
main: error: Parser key "model.model": Problem with given class_path 'models.MyModel':
    - Parser key "gnn": Does not validate against any of the Union subtypes
      Subtypes: (<class 'torch.nn.modules.module.Module'>, <class 'NoneType'>)
      Errors:
        - Problem with given class_path 'models.Transformer':
          - Parser key "attention": Problem with given class_path 'models.ScaledDotProductAttention':
              - 'Configuration check failed :: No action for destination key "num_heads" to check its value.'
        - Expected a <class 'NoneType'>
      Given value type: <class 'jsonargparse.namespace.Namespace'>
      Given value: Namespace(class_path='models.Transformer', init_args=Namespace(embed_dim=128, num_heads=8, num_layers=6, attention=Namespace(class_path='models.ScaledDotProductAttention', init_args=Namespace(num_heads=8, head_dim=16)), activation='SiLU', out_dim=128, residual=True, norm_layer='LayerNorm', dropout=0.1, out_proj=False))
```

**Comment by mauvilsa** [comment]
@samvanstroud could you please create a minimal reproduction script. With just the error message it is difficult for me to understand what exactly the issue is and how your case differs to the unit test that I wrote.

**Comment by samvanstroud** [comment]
Here is a code

```python
# test.py
import pytorch_lightning as pl
import torch.nn as nn
from pytorch_lightning.cli import LightningCLI
from pytorch_lightning.demos.boring_classes import BoringDataModule, DemoModel


class SubA(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(x):
        return x


class SubB(nn.Module):
    def __init__(self, arg: int):
        super().__init__()

        self.arg = arg

    def forward(x):
        return x


class MyModel(DemoModel):
    def __init__(self, model: nn.Module):
        super().__init__()
        self.model = model


def cli_main():
    cli = LightningCLI(MyModel, BoringDataModule)


if __name__ == "__main__":
    cli_main()
```

This runs fine with 
```bash
python test.py fit --trainer.fast_dev_run 2 --model.model SubB --model.model.arg 1 --model.model SubA
```

But, if we create two yaml files
```yaml
# A.yaml
model:
    model:
        class_path: SubA
```
and 
```yaml
# B.yaml
model:
    model:
        class_path: SubB
        init_args:
            arg: 1
```
then 
```bash
python test.py fit --trainer.fast_dev_run 2 --config A.yaml --config B.yaml
```
runs fine, but
```bash
python test.py fit --trainer.fast_dev_run 2 --config B.yaml --config A.yaml
```
errors with 
```bash
.../python3.10/site-packages/jsonargparse/typehints.py:909: UserWarning: Due to class_path change from '__main__.SubB' to '__main__.SubA', discarding init_args: {'arg': 1}.
  warnings.warn(
usage: test.py [-h] [-c CONFIG] [--print_config[=flags]] {fit,validate,test,predict,tune} ...
test.py: error: Parser key "model.model": Problem with given class_path '__main__.SubA':
    - 'Configuration check failed :: No action for destination key "arg" to check its value.'
```

**Comment by samvanstroud** [comment]
Also, would you consider the possibility to suppress the warning? e.g.

`.../python3.10/site-packages/jsonargparse/typehints.py:909: UserWarning: Due to class_path change from '__main__.SubB' to '__main__.SubA', discarding init_args: {'arg': 1}.`

**Comment by mauvilsa** [comment]
> Also, would you consider the possibility to suppress the warning?

In some time I will convert this to a log at debug level, since I need this to be visible somehow to identify problems like this one. But I am not doing this right now because that requires more work. For the time being you can suppress the warning how any warning in python is suppressed.

**Comment by mauvilsa** [comment]
@samvanstroud thank you for the code snippet. I tired it all worked correctly. Are you sure you tested with the branch from this pull request?

**Comment by samvanstroud** [comment]
Ah apologies, looks like pip did not actually perform the install since the version requirement was already satisfied. After uninstalling and re-installing everything is working, thanks a lot!

**Pull request merged**
